#!/bin/bash

if [ $USER != 'root' ]; then
  echo "You must be root to run this script..."
  exit -1
fi

echo -n "fish, tmux, and vim will be installed. Are you sure you want to continue? [y/n] "

read answer

if [ $answer != "y" ]; then
  echo "Exiting..."
  exit 1
fi

echo "Installing required programs..."

apt-get install fish tmux vim -y

echo "Installing oh-my-fish"

su taytek -c "curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish"

echo "Downloading files... (DO NOT EXIT)"

git clone https://github.com/taylortek/DotFiles &>/dev/null

echo "Setting up config files and permissions..."

chown -R taytek:taytek DotFiles

su taytek -c "cp DotFiles/config.fish /home/taytek/.config/fish/; cp DotFiles/tmux.conf /home/taytek/.tmux.conf; rm ~/.vim -fr && cp DotFiles/vim ~/.vim -r ; chsh -s `which fish`"

echo "Cleaning up..."

rm -fr DotFiles

echo "You're all set!"
